// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recipientservice.proto
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace AbstractBinding.Examples.Protos {
  /// <summary>
  /// The Recipient service definition.
  /// </summary>
  public static partial class RecipientService
  {
    static readonly string __ServiceName = "AbstractBinding.Examples.Protobufs.RecipientService";

    static readonly grpc::Marshaller<global::AbstractBinding.Examples.Protos.RequestMessage> __Marshaller_RequestMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AbstractBinding.Examples.Protos.RequestMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AbstractBinding.Examples.Protos.ResponseMessage> __Marshaller_ResponseMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AbstractBinding.Examples.Protos.ResponseMessage.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AbstractBinding.Examples.Protos.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AbstractBinding.Examples.Protos.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::AbstractBinding.Examples.Protos.NotificationMessage> __Marshaller_NotificationMessage = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::AbstractBinding.Examples.Protos.NotificationMessage.Parser.ParseFrom);

    static readonly grpc::Method<global::AbstractBinding.Examples.Protos.RequestMessage, global::AbstractBinding.Examples.Protos.ResponseMessage> __Method_Request = new grpc::Method<global::AbstractBinding.Examples.Protos.RequestMessage, global::AbstractBinding.Examples.Protos.ResponseMessage>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Request",
        __Marshaller_RequestMessage,
        __Marshaller_ResponseMessage);

    static readonly grpc::Method<global::AbstractBinding.Examples.Protos.Empty, global::AbstractBinding.Examples.Protos.NotificationMessage> __Method_Listen = new grpc::Method<global::AbstractBinding.Examples.Protos.Empty, global::AbstractBinding.Examples.Protos.NotificationMessage>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Listen",
        __Marshaller_Empty,
        __Marshaller_NotificationMessage);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::AbstractBinding.Examples.Protos.RecipientserviceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RecipientService</summary>
    public abstract partial class RecipientServiceBase
    {
      /// <summary>
      /// Performs request
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::AbstractBinding.Examples.Protos.ResponseMessage> Request(global::AbstractBinding.Examples.Protos.RequestMessage request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Subscribes for notifications
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task Listen(global::AbstractBinding.Examples.Protos.Empty request, grpc::IServerStreamWriter<global::AbstractBinding.Examples.Protos.NotificationMessage> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RecipientService</summary>
    public partial class RecipientServiceClient : grpc::ClientBase<RecipientServiceClient>
    {
      /// <summary>Creates a new client for RecipientService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RecipientServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RecipientService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RecipientServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RecipientServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RecipientServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Performs request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AbstractBinding.Examples.Protos.ResponseMessage Request(global::AbstractBinding.Examples.Protos.RequestMessage request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Request(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Performs request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::AbstractBinding.Examples.Protos.ResponseMessage Request(global::AbstractBinding.Examples.Protos.RequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Request, null, options, request);
      }
      /// <summary>
      /// Performs request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AbstractBinding.Examples.Protos.ResponseMessage> RequestAsync(global::AbstractBinding.Examples.Protos.RequestMessage request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return RequestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Performs request
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::AbstractBinding.Examples.Protos.ResponseMessage> RequestAsync(global::AbstractBinding.Examples.Protos.RequestMessage request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Request, null, options, request);
      }
      /// <summary>
      /// Subscribes for notifications
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::AbstractBinding.Examples.Protos.NotificationMessage> Listen(global::AbstractBinding.Examples.Protos.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Listen(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Subscribes for notifications
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::AbstractBinding.Examples.Protos.NotificationMessage> Listen(global::AbstractBinding.Examples.Protos.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Listen, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RecipientServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RecipientServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RecipientServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Request, serviceImpl.Request)
          .AddMethod(__Method_Listen, serviceImpl.Listen).Build();
    }

  }
}
#endregion
